* Generated by FormCode.nb

id Chain(UBar1,G(E2),U0) = chains4D((1));

id Chain(UBar1,G(E3),U0) = chains4D((2));

id Chain(UBar1,G(p2),U0) = chains4D((3));

id Chain(UBar1,G(p3),U0) = chains4D((4));

id Chain(UBar1,G(E2,E3,p3),U0) = chains4D((5));

id Chain(UBar1,G(p2,E2,E3),U0) = chains4D((6));

id Chain(UBar1,G(p2,E2,p3),U0) = chains4D((7));

id Chain(UBar1,G(p2,E3,p3),U0) = chains4D((8));

id Chain(UBar2,G(E0),V3) = chains4D((9));

id Chain(UBar2,G(E1),V3) = chains4D((10));

id Chain(UBar2,G(p1),V3) = chains4D((11));

id Chain(UBar2,G(n),V3) = chains4D((12));

id Chain(UBar2,G(E1,E0,n),V3) = chains4D((13));

id Chain(UBar2,G(p1,E0,n),V3) = chains4D((14));

id Chain(UBar2,G(p1,E1,E0),V3) = chains4D((15));

id Chain(UBar2,G(p1,E1,n),V3) = chains4D((16));

id Chain(UBar1,G(mu),U0,UBar2,G(mu),V3) = chains4D((17));

id Chain(UBar1,G(mu),U0,UBar2,G(p1,mu,n),V3) = chains4D((18));

id Chain(UBar1,G(p2),U0,UBar2,G(p1),V3) = chains4D((19));

id Chain(UBar1,G(p2),U0,UBar2,G(n),V3) = chains4D((20));

id Chain(UBar1,G(p3),U0,UBar2,G(p1),V3) = chains4D((21));

id Chain(UBar1,G(p3),U0,UBar2,G(n),V3) = chains4D((22));

id Chain(UBar1,G(mu1,mu2,mu3),U0,UBar2,G(mu1,mu2,mu3),V3) = chains4D((23));

id Chain(UBar1,G(nu1,nu2,p3),U0,UBar2,G(nu1,nu2,n),V3) = chains4D((24));

id Chain(UBar1,G(nu1,nu2,p3),U0,UBar2,G(p1,nu1,nu2),V3) = chains4D((25));

id Chain(UBar1,G(p2,mu,p3),U0,UBar2,G(mu),V3) = chains4D((26));

id Chain(UBar1,G(p2,mu,p3),U0,UBar2,G(p1,mu,n),V3) = chains4D((27));

id Chain(UBar1,G(p2,nu1,nu2),U0,UBar2,G(nu1,nu2,n),V3) = chains4D((28));

id Chain(UBar1,G(p2,nu1,nu2),U0,UBar2,G(p1,nu1,nu2),V3) = chains4D((29));

id Chain(UBar2,G(mu),U0,UBar1,G(mu),V3) = chains4D((30));

id Chain(UBar2,G(mu),U0,UBar1,G(p2,mu,n),V3) = chains4D((31));

id Chain(UBar2,G(p1),U0,UBar1,G(p2),V3) = chains4D((32));

id Chain(UBar2,G(p1),U0,UBar1,G(n),V3) = chains4D((33));

id Chain(UBar2,G(p3),U0,UBar1,G(p2),V3) = chains4D((34));

id Chain(UBar2,G(p3),U0,UBar1,G(n),V3) = chains4D((35));

id Chain(UBar2,G(mu1,mu2,mu3),U0,UBar1,G(mu1,mu2,mu3),V3) = chains4D((36));

id Chain(UBar2,G(nu1,nu2,p3),U0,UBar1,G(nu1,nu2,n),V3) = chains4D((37));

id Chain(UBar2,G(nu1,nu2,p3),U0,UBar1,G(p2,nu1,nu2),V3) = chains4D((38));

id Chain(UBar2,G(p1,mu,p3),U0,UBar1,G(mu),V3) = chains4D((39));

id Chain(UBar2,G(p1,mu,p3),U0,UBar1,G(p2,mu,n),V3) = chains4D((40));

id Chain(UBar2,G(p1,nu1,nu2),U0,UBar1,G(nu1,nu2,n),V3) = chains4D((41));

id Chain(UBar2,G(p1,nu1,nu2),U0,UBar1,G(p2,nu1,nu2),V3) = chains4D((42));

