* Generated by FormCode.nb

#do i=0,3
#do j={`i'+1},3
id E`i'.E`j'= den(p3n^2*s12^2-2*p2n*p3n*s12*s13+p2n^2*s13^2-2*p1n*p3n*s12*s23-2*p1n*p2n*s13*s23+p1n^2*s23^2)*(E`i'.p3*(s12*(p3n*s12-p2n*s13-p1n*s23)*E`j'.n+2*p2n*(-(p3n*s12)+p2n*s13-p1n*s23)*E`j'.p1+2*p1n*(-(p3n*s12)-p2n*s13+p1n*s23)*E`j'.p2+4*p1n*p2n*s12*E`j'.p3)+E`i'.p1*(-(s23*(p3n*s12+p2n*s13-p1n*s23)*E`j'.n)+4*p2n*p3n*s23*E`j'.p1+2*p3n*(p3n*s12-p2n*s13-p1n*s23)*E`j'.p2+2*p2n*(-(p3n*s12)+p2n*s13-p1n*s23)*E`j'.p3)+E`i'.p2*(-(s13*(p3n*s12-p2n*s13+p1n*s23)*E`j'.n)+2*p3n*(p3n*s12-p2n*s13-p1n*s23)*E`j'.p1+4*p1n*p3n*s13*E`j'.p2+2*p1n*(-(p3n*s12)-p2n*s13+p1n*s23)*E`j'.p3));
#enddo
#enddo
