* Generated by FormCode.nb

#do i=1,3
id once G(mu?{mu,nu1,nu2,mu1,mu2,mu3}) = den(p3n^2*s12^2-2*p2n*p3n*s12*s13+p2n^2*s13^2-2*p1n*p3n*s12*s23-2*p1n*p2n*s13*s23+p1n^2*s23^2)*(G(p3)*(s12*(p3n*s12-p2n*s13-p1n*s23)*n(mu)+2*p2n*(-(p3n*s12)+p2n*s13-p1n*s23)*p1(mu)+2*p1n*(-(p3n*s12)-p2n*s13+p1n*s23)*p2(mu)+4*p1n*p2n*s12*p3(mu))+G(n)*(s12*s13*s23*n(mu)-s23*(p3n*s12+p2n*s13-p1n*s23)*p1(mu)-s13*(p3n*s12-p2n*s13+p1n*s23)*p2(mu)+s12*(p3n*s12-p2n*s13-p1n*s23)*p3(mu))+G(p1)*(-(s23*(p3n*s12+p2n*s13-p1n*s23)*n(mu))+4*p2n*p3n*s23*p1(mu)+2*p3n*(p3n*s12-p2n*s13-p1n*s23)*p2(mu)+2*p2n*(-(p3n*s12)+p2n*s13-p1n*s23)*p3(mu))+G(p2)*(-(s13*(p3n*s12-p2n*s13+p1n*s23)*n(mu))+2*p3n*(p3n*s12-p2n*s13-p1n*s23)*p1(mu)+4*p1n*p3n*s13*p2(mu)+2*p1n*(-(p3n*s12)-p2n*s13+p1n*s23)*p3(mu)));
#enddo

#do i=0,3
id G(E`i') = den(p3n^2*s12^2-2*p2n*p3n*s12*s13+p2n^2*s13^2-2*p1n*p3n*s12*s23-2*p1n*p2n*s13*s23+p1n^2*s23^2)*((-(s23*(p3n*s12+p2n*s13-p1n*s23)*E`i'.p1)-s13*(p3n*s12-p2n*s13+p1n*s23)*E`i'.p2+s12*(p3n*s12-p2n*s13-p1n*s23)*E`i'.p3)*G(n)+(4*p2n*p3n*s23*E`i'.p1+2*p3n*(p3n*s12-p2n*s13-p1n*s23)*E`i'.p2+2*p2n*(-(p3n*s12)+p2n*s13-p1n*s23)*E`i'.p3)*G(p1)+(2*p3n*(p3n*s12-p2n*s13-p1n*s23)*E`i'.p1+4*p1n*p3n*s13*E`i'.p2+2*p1n*(-(p3n*s12)-p2n*s13+p1n*s23)*E`i'.p3)*G(p2)+(2*p2n*(-(p3n*s12)+p2n*s13-p1n*s23)*E`i'.p1+2*p1n*(-(p3n*s12)-p2n*s13+p1n*s23)*E`i'.p2+4*p1n*p2n*s12*E`i'.p3)*G(p3));
#enddo
