* Generated by FormCode.nb

id Int(DS(k)*DS(k+p3)*DS(k+p3+p4)) = (-2/s34-(2*den(-4+d))/s34)*Int(DS(k)*DS(k+p3+p4));

id Int(DS(k)*DS(k+p4)*DS(k+p3+p4)) = (-2/s34-(2*den(-4+d))/s34)*Int(DS(k)*DS(k+p3+p4));

id Int(DS(k)*DS(k+p3+p4)*Eik(k,p1)) = (-4-4*den(-4+d))*den(s13+s14)*Int(DS(k)*DS(k+p3+p4));

id Int(DS(k)*DS(k+p3+p4)*Eik(k,p2)) = (-4-4*den(-4+d))*den(s23+s24)*Int(DS(k)*DS(k+p3+p4));

id Int(DS(k)*DS(k+p3+p4)*Eik(k+p3+p4,p1)) = (4+4*den(-4+d))*den(s13+s14)*Int(DS(k)*DS(k+p3+p4));

id Int(DS(k)*DS(k+p3+p4)*Eik(k+p3+p4,p2)) = (4+4*den(-4+d))*den(s23+s24)*Int(DS(k)*DS(k+p3+p4));

