kinematics:
  incoming_momenta: []
  outgoing_momenta: ["p1","p2","p3","p4"]
  momentum_conservation: []
  kinematic_invariants:
  - ["s12",2]
  - ["s13",2]
  - ["s14",2] 
  - ["s23",2]
  - ["s24",2] 
  - ["s34",2]
  scalarproduct_rules:
  - [["p1","p1"],0]
  - [["p2","p2"],0]
  - [["p3","p3"],0]
  - [["p4","p4"],0]
  - [["p1","p2"],"s12/2"]
  - [["p1","p3"],"s13/2"]
  - [["p1","p4"],"s14/2"]
  - [["p2","p3"],"s23/2"] 
  - [["p2","p4"],"s24/2"]
  - [["p3","p4"],"s34/2"]
